# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: databricks-launch

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      # Prepare environment
      - name: Install and test Databricks CLI
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
        run: |
          python -m pip install databricks-cli
          databricks clusters list
